#!/usr/bin/env node
/**
 * Freezes the current docs content into docs/src/docs/versions/<version>.ts
 * Run this BEFORE bumping package.json when cutting a release, so the old
 * version stays readable in the version dropdown forever.
 *
 *   node scripts/snapshot-docs.mjs 1.0.2
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const version = process.argv[2];
if (!version) {
  console.error('usage: node scripts/snapshot-docs.mjs <version>');
  process.exit(1);
}

const root = fileURLToPath(new URL('../', import.meta.url));
const contentPath = `${root}docs/src/docs/content.ts`;
const outDir = `${root}docs/src/docs/versions`;
const indexPath = `${outDir}/index.ts`;

let content = readFileSync(contentPath, 'utf8');

// extract the sections array body from content.ts
const sectionsMarker = 'sections: [';
const start = content.indexOf(sectionsMarker);
if (start === -1) {
  console.error('could not locate sections in content.ts');
  process.exit(1);
}
// match balanced brackets: open at the [ right after 'sections: '
const openIdx = content.indexOf('[', start);
let depth = 0;
let end = -1;
for (let i = openIdx; i < content.length; i++) {
  if (content[i] === '[') depth++;
  else if (content[i] === ']') {
    depth--;
    if (depth === 0) {
      end = i;
      break;
    }
  }
}
if (end === -1) {
  console.error('unbalanced sections array');
  process.exit(1);
}
// include the outer opening bracket, exclude nothing else
let sectionsBody = content.slice(openIdx, end + 1);
// freeze the current-version template literal to the archived version.
sectionsBody = sectionsBody.replaceAll('${CURRENT_VERSION}', version);

const importName = `v${version.replace(/\./g, '_')}`;
const outFile = `${outDir}/${importName}.ts`;
if (existsSync(outFile)) {
  console.log(`version ${version} already archived, skipping`);
  process.exit(0);
}

writeFileSync(
  outFile,
  `// Frozen docs for v${version}. Generated by scripts/snapshot-docs.mjs.
import type { DocSection } from '../content';

export const ${importName}_SECTIONS: DocSection[] = ${sectionsBody};
`,
);

// register in the archive index
let index = readFileSync(indexPath, 'utf8');
if (!index.includes(importName)) {
  index = index.replace(
    "import type { DocVersion } from '../content';",
    `import type { DocVersion } from '../content';
import { ${importName}_SECTIONS } from './${importName}.js';`,
  );
  index = index.replace(
    'export const ARCHIVED_VERSIONS: DocVersion[] = [];',
    `export const ARCHIVED_VERSIONS: DocVersion[] = [
  { version: '${version}', label: 'v${version}', sections: ${importName}_SECTIONS },
];`,
  );
  writeFileSync(indexPath, index);
}
console.log(`archived docs for v${version}`);
